---
- name: Install Unzip
  apt:
    update_cache: yes
    name: zip
    state: present

- name: Get Latest Yara Release
  uri:
    url: https://api.github.com/repos/VirusTotal/yara/releases/latest
  register: yara_release

- name: Download Yara Release
  get_url:
    url: "https://github.com/VirusTotal/yara/archive/refs/tags/{{ yara_release.json.tag_name }}.zip"
    dest: /tmp/yara.zip

- name: Unzip Release
  unarchive:
    src: /tmp/yara.zip
    dest: /tmp
    remote_src: yes
    creates: "yara-{{ yara_release.json.tag_name | regex_replace('v') }}"
  register: yara_folder
  changed_when: false


- name: Install Required Packages
  apt:
    name: "{{ required_packages }}"
    state: present
  become: yes

- name: Install Module Dependent Packages
  include_tasks: package_modules.yml

- name: Run Bootstrap
  command:
    chdir: "/tmp/yara-{{ yara_release.json.tag_name | regex_replace('v') }}"
    cmd: ./bootstrap.sh
  changed_when: false

- name: Run configure command with appropriate flags
  ansible.builtin.shell:
    chdir: "/tmp/yara-{{ yara_release.json.tag_name | regex_replace('v') }}"
    cmd: >
      ./configure
      {{ ' --with-crypto' if enable_ssl }}
      {{ ' --enable-cuckoo' if enable_cuckoo }}
      {{ ' --enable-magic' if enable_magic }}
      {{ ' --enable-dotnet' if enable_dotnet }}

- name: Run Makefile
  make:
    chdir: "/tmp/yara-{{ yara_release.json.tag_name | regex_replace('v') }}"

- name: Install Makefile
  make:
    chdir: "/tmp/yara-{{ yara_release.json.tag_name | regex_replace('v') }}"
    target: install
  changed_when: false
  become: yes

- name: Verify Makefile
  make:
    chdir: "/tmp/yara-{{ yara_release.json.tag_name | regex_replace('v') }}"
    target: check
  register: verify_make
  failed_when: "'ERROR: 0' not in verify_make.stdout"
  changed_when: false
  become: yes

- name: Ensure libyara Is Configured
  command: ldconfig
  become: yes
  changed_when: false
