---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify Yara Can Run
    command:
      cmd: /usr/local/bin/yara -v
    register: yara_version
    changed_when: "'4.1' in yara_version.stdout"
